# Version of Docker-compose
version: '3.9'
services:
  slr-server:
    build:
      context: ./server
    ports:
      - '5000:5000'
    depends_on:
      - mongo
    environment:
      MONGODB_URI: mongodb://mongo:27017/slr

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
